# Copyright 2018 JanusGraph Python Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: python

python:
- '3.6'
- '3.5'
- '3.4'
- '3.7'
- '3.8'

install:
  - pip install virtualenv
  # Installs virtualenv which is pre requisite for building this library. All other dependencies will be installed inside

#before_script:
  # Install all pre-requisites for building library and docs

script:
  - bash build.sh -b true -d true -p python3

# Deployment to PyPi configuration
# TODO: Update personal credentials for publishing to PyPi with JanusGraph user credentials.
branches:
  only:
  - master
  - basic-pr
before_deploy:
  - cd target/dist/janusgraph_python
deploy:
  provider: pypi
  user:
  password:
  server: https://test.pypi.org/legacy/
  skip_cleanup: true
  on:
    tags: true
